# Generated by Django 2.2.17 on 2021-03-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potform', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='supervisor',
        #     name='user',
        # ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
