# Generated by Django 2.2.17 on 2021-03-15 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potform', '0003_user_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date_from', models.DateTimeField()),
                ('request_date_to', models.DateTimeField()),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('chose_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chose_supervisor', to=settings.AUTH_USER_MODEL)),
                ('post_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
