# Generated by Django 2.2.17 on 2021-03-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potform', '0004_requestpto'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpto',
            name='request',
            field=models.IntegerField(default=3),
        ),
    ]
