# Generated by Django 2.2.17 on 2021-03-22 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potform', '0005_requestpto_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpto',
            name='confirm_hr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_hr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
