# Generated by Django 2.2.17 on 2021-03-22 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potform', '0006_requestpto_confirm_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpto',
            name='confirm_hr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirm_hr', to=settings.AUTH_USER_MODEL),
        ),
    ]
